name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set PYTHONPATH for all platforms
      run: |
        echo "Setting PYTHONPATH..."
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
        echo "PYTHONPATH is: $PYTHONPATH"
        echo "Current working directory: $(pwd)"
        echo "List of installed Python packages:"
        pip list

#    - name: Set PYTHONPATH for Linux/macOS
#      if: runner.os != 'Windows'
#      run: |
#        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
#
#    - name: Set PYTHONPATH for Windows
#      if: runner.os == 'Windows'
#      run: |
#        echo "Setting PYTHONPATH for Windows..."
#        powershell -Command "[System.Environment]::SetEnvironmentVariable('PYTHONPATH', '${PWD}', [System.EnvironmentVariableTarget]::Process)"
#        echo "PYTHONPATH is: $env:PYTHONPATH"
#        echo "Current working directory: $PWD"
#        echo "List of installed Python packages:"
#        powershell -Command "pip list"
        

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install modules
      run: |
        python -m pip install --upgrade pip
        python -m pip install flask pytest pytest-cov

    - name: Run tests
      run: |
        pytest --cov=redirect_flask_app tests/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 185.242.106.225 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no jew2000@185.242.106.225 <<EOF
          cd /tmp
          git pull origin main
      
          pip3 install flask pytest pytest-cov

          sudo cp service/flask-redirect.service /etc/systemd/system/flask-redirect.service
      
          sudo systemctl daemon-reload; sudo systemctl enable --now flask-redirect.service
          sudo systemctl status flask-redirect.service --no-pager
        EOF
